/* Plugin generated by AMXX-Studio */

#include <amxmodx>
#include <amxmisc>
#include <fakemeta_util>
#include <hamsandwich>

#define IsPlayer(%1) ( 1 <= %1 <= 32 )

#define PLUGIN "Advanced Bullet Damage"
#define VERSION "1.0"
#define AUTHOR "Sn!ff3r"

new g_pcvar_type, g_type_value, g_hudmsg1, g_hudmsg2

public plugin_init() 
{
	register_plugin(PLUGIN, VERSION, AUTHOR)
	
	register_event("Damage", "on_damage", "b", "2!0", "3=0", "4!0")	;
	register_event("HLTV", "on_new_round", "a", "1=0", "2=0");
	RegisterHam(Ham_TakeDamage, "info_target", "fw_info_target_damage", .Post = true);

	
	g_pcvar_type = register_cvar("amx_bulletdamage", "3");
	
	g_hudmsg1 = CreateHudSyncObj();
	g_hudmsg2 = CreateHudSyncObj();
}

public fw_info_target_damage(id, inflictor, attacker, Float:fDamage, iDamageBits)
{
	DisplayHudMessageDamage(id, attacker, floatround(fDamage));
}

public on_new_round()
{
	g_type_value = get_pcvar_num(g_pcvar_type);
}

public on_damage(id)
{
	DisplayHudMessageDamage(id, get_user_attacker(id), read_data(2));
}

DisplayHudMessageDamage(const id, const attacker, const damage)
{
	if(g_type_value > 0)
	{
		if( IsPlayer(id) )
		{
			if((g_type_value & 1) )
			{
				if(damage > 0)
					set_hudmessage(255, 0, 0, 0.45, 0.50, 2, 0.1, 4.0, 0.1, 0.1, -1);
				else
					set_hudmessage(0, 255, 0, 0.45, 0.50, 2, 0.1, 4.0, 0.1, 0.1, -1);
				ShowSyncHudMsg(id, g_hudmsg2, "%i^n", damage);
			}
		}

		if( IsPlayer(attacker) )
		{
			if((g_type_value & 2))
			{
				if(damage > 0)
					set_hudmessage(0, 100, 200, -1.0, 0.55, 2, 0.1, 4.0, 0.02, 0.02, -1);
				else
					set_hudmessage(0, 200, 0, -1.0, 0.55, 2, 0.1, 4.0, 0.02, 0.02, -1);
				ShowSyncHudMsg(attacker, g_hudmsg1, "%i^n", damage);
			}
			else if((g_type_value & 4))
			{
				if(fm_is_ent_visible(attacker,id))
				{
					if(damage > 0)
						set_hudmessage(0, 100, 200, -1.0, 0.55, 2, 0.1, 4.0, 0.02, 0.02, -1);
					else
						set_hudmessage(0, 200, 0, -1.0, 0.55, 2, 0.1, 4.0, 0.02, 0.02, -1);
					ShowSyncHudMsg(attacker, g_hudmsg1, "%i^n", damage);
				}
			}
		}
	}
}
/* AMXX-Studio Notes - DO NOT MODIFY BELOW HERE
*{\\ rtf1\\ ansi\\ deff0{\\ fonttbl{\\ f0\\ fnil Tahoma;}}\n\\ viewkind4\\ uc1\\ pard\\ lang1045\\ f0\\ fs16 \n\\ par }
*/
