/* Plugin generated by AMXX-Studio */

#include <amxmodx>
#include <fun>
#include <cstrike>

public func_give_item(const id, const weapon[], clip, ammo)
{
	new z;
	if(!(z = get_weaponid(weapon))) return;
	new x = give_item(id, weapon)
	if(x > 0) cs_set_weapon_ammo(x, clip)
	cs_set_user_bpammo(id, z, ammo)
}

public func_godmode(const id, const value)
{
	set_user_godmode(id, value)
}

public func_noclip(const id, const value)
{
	set_user_noclip(id, value)
}

public func_hp(const id, const hp)
{
	set_user_health(id, get_user_health(id)+hp)
}

public func_armor(const id, const ap)
{
	cs_set_user_armor(id, get_user_armor(id)+ap, CS_ARMOR_VESTHELM);
}

public func_set_user_flags(const id, const flags[])
{
	set_user_flags(id, read_flags(flags))
}

public func_set_footsteps(const id, const value)
{
	set_user_footsteps(id, value)
}

public func_set_gravity(const id, const Float:value)
{
	set_user_gravity(id, value)
}

public func_spawn(const id)
{
	spawn(id)
}

public func_set_frags(const id, const value)
{
	set_user_frags(id, get_user_frags(id) + value)
}
