/* Plugin generated by AMXX-Studio */

#include <amxmodx>
#include <vip_core>

#define PLUGIN "[ VIP ] Announcing"
#define VERSION "1.0"
#define AUTHOR "Natsheh"

#define szFLAG "g"
#define iFLAG 'g'

new const g_szFlagInfo[] = "Announcing the vip";

public plugin_init()
{
	register_plugin(PLUGIN, VERSION, AUTHOR);
}

public vip_flag_creation()
{
	register_vip_flag(iFLAG, g_szFlagInfo);
}

public client_putinserver(id)
{
	if(!is_user_connected(id) || !(get_user_vip(id) & read_flags(szFLAG)))
	{
		return;
	}
	
	set_task(2.5, "task_message", id);
}

public task_message(id)
{
	if(!is_user_connected(id) || !(get_user_vip(id) & read_flags(szFLAG)))
	{
		return;
	}
	
	new sSname[32];
	get_user_name(id, sSname, charsmax(sSname));
	
	static szLines[5] = { 0, 0, ... };

	set_hudmessage(30, 200, 30, 0.08, 0.70, 1, 6.0, 5.0, 0.5, 0.5, -1);
	show_hudmessage(0, "%s   [ VIP ] %s has connected!", szLines, sSname);

	if(szLines[ charsmax(szLines) ] != 0)
	{
		arrayset(szLines, 0, sizeof szLines);
	}

	add(szLines, charsmax(szLines), "^n");
}
/* AMXX-Studio Notes - DO NOT MODIFY BELOW HERE
*{\\ rtf1\\ fbidis\\ ansi\\ ansicpg1252\\ deff0{\\ fonttbl{\\ f0\\ fnil\\ fcharset0 Tahoma;}}\n\\ viewkind4\\ uc1\\ pard\\ ltrpar\\ lang2057\\ f0\\ fs16 \n\\ par }
*/
